language: ruby
rvm:
  - "2.4.0"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs
