language: ruby
rvm:
- 2.4.0
env:
  matrix:
  - DB=postgresql
  global:
  - secure: hLUhZzSZVBt2yohuvIoB1e9gdl3qbOPYysr9ICgXlvEit/90psv6/K7FqD4nCVWmGLb2DbDBukybET0RqLTEGJjFnN5kViT/nbi7t4MD2zTi6SwkGlwUlIUl7jHhrc3y3Lxq73mMsBD6l2ngfOkfayzQwG2/BtFcrBewGxG8hqnDa/8+j7yN6x1VQMI/StcC+OUzzVvZCCFz7N4a+lh1WMeiM4fqv9O4HsFBTTgDdp9aAj+qZO7CpP9Pyv2olcik3d8/oELHgSe541utUHrkwfTL5B7Cv3U9q83Y2s5oUPEu804gGRnnstQ3WWC/OUJbZw4Fd5p+dmW3DkYkgOhfHGjKTg91IfiZ2iAOWikE4SAd5JHC4g2ntBYGqhlqdj4DFwJ0gLmplZiwQOCeG/wPqXLXPila/QZobsb8T63ysmx1eascj4U+av8LYynM0e0T73RxxHSjaWPuJr1CUk9II7gV9kLaPh38O1jVrjKMexd0QuUVlo4+aC23Yy/7+d/sRPFbSr8YsfeU8X0uKJ5/qyK/xYK607kjw91TBK8h+wPfynQ2Px24z1F+w8pchUYGq0CJAO19vcHgFoYiWXDgAiqGQH8hs4TsTWTNPy3hInGhWjNdECWPpo1sLCX9reekMNCmchYaPkVxEgDX26cSrJ0aQoE93kwL5df3ATsxKoU=
  - secure: GvxasSobXwlyuZKNcEgkG8EbjdY0699TuE7/Pz/QFOw2YCaY4MBjoclSbuAQTeAZPgepSge9tdm3n1gp5DrSqbzOy+NZxiquHhPI5PpUsa+5CpczvNDqOCCObH+9uCb7hw+SbmQKOyHJzgGUNJ0jySAs/XDbPH0+v61QtWeI/EWX2EJWcoRIbUMxpDm0Chvlhq8MniRM67+fTzHlKn1UCRqvt/3/0ptSAXoLXezYJGdAh2rraN2D9s51P3ZUCbs7aeVQqILDmi97wEMUJDW2dfIHyx7CqTjjvrtimlacmDYhy/WmqnYdPjuNL95cMlXHLygEWdp1uvOgsPbmRnGwou21B9R3KcSQutOSX9QAeEgwcyhlSZbVzzkIdOG2DwqKUQL4v4VAA+flArIOirS3HIkUbpsgOcWMDoXB2BjPYbPUZ05gKq6ijSfsKX5JrKj+0IorqHdygB4L4/gktQzuCQ3QI4R5RNimC7khziYsg/PKOYiVBGvoWfoRJAYGJ5fJOUE8wWRupeED/m4VN1/KPozwC2jw8Z01k1PPJ3+iNzBW7GPwF5/r5kA2LHZhllE3BF73PYYgshD6G+ZiB4x6PahLVnmqBdkGZSkC7SCMLha5v/aoSfv5fJQ6AaYhNKOPFMbjBYzPmQrCNU8LOy2nFsHA6BL5uKBy4uB9lCNc/ps=
script:
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
- bundle exec rspec
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: i80Mv9n8wjtZ8EQWG/QD9EdKdZ+l2qm0e7zn6YUE6teUZGm388xTncFN5/RzSaO1YBHN76uD42L0z0Feb1uPeG8lmYbb5r+W4hGfckD/+Gp+ktiFn5RKqin7eyRbxBUoN+EOmdLWKQHL7Y1sDCdNacawRIkej5plWeYvLB+ndQmK8DqBsLDLi51S99QjnYNdaTU9DW8S8TAjDyUOX7SOjUZkzDYvBDZRnkEf0hEvqnU2AwNI327hMuQecWQMqWk9QpmuB3z6mZKLCtPEKWziEIeD3K+6MWilw+1Q/4+4j2edVLmgOKB+KSo1utf5nPMs9IQJ+ve95dvY8iIv4r61AVifjyAo3gcH4gG2GxN4S1eLxA4IBJSBonepxHIASi7vxsB64GqtrV8R3CuhM1ybq786JteDyViSGqyT3LnnT57F+S8lQFOm1f4z1HcoKR+JtfM43X2p/AH2QUBjh2r5GByDmESwZ7lvuIVPy33FGTn72i/tXB1ygxz2jQciji8g2H33I1KkhjXyYXawjgaCL+yTi+pxEG4ML2rTwoH8+e/yzu7YCTq831A5K4iuu8kMGTyUIYwrJJrapWvbH3q4mpnxT26QBinymcIHusfpQtYEk7nyWzQLHxcWICH02ujNpvESA9PXw0Km7FqO+Gvj/gjv3O/C+s8JZsnO2r88tsE=
  app: poker-season
  on:
    repo: notmarkmiranda/v5_pokerrank
